person:
  name: "John Doe"


pet:
  name: "曲奇"
  type: "哈士奇"
  friends: [ "小白", "小黑" ]
  score:
    math: 90
    english: 80
    chinese: 70

  category:
    name: "dog"
    type: "哈士奇"

  hobbies: [ "吃饭", "睡觉", "打豆豆" ]



# exp6

spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.20.193.205:3300/springtest
    username: springtest
    password: wH284GhZaHd6b5jt
    type: com.alibaba.druid.pool.DruidDataSource

    # druid
    druid:
      initial-size: 0
      min-idle: 10
      max-active: 10

  data:
    redis:
      host: 172.20.193.205
      port: 6379
      password: redis_GWdBSf

  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html


  messages:
    basename: i18n.login

mybatis:
  configuration:
    map-underscore-to-camel-case: true # enable camel case
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.exp_six.domain